### PR TITLE
fix: button styles, picture add product && form add product

### LINKED ISSUE #229: Eliminar el botón Eliminar en la vista de creación de productos /Remove delete button in product creation view
**Explanation**

al ingresar la vista de productos e ir a creación de producto, salen dos botones, estos son eliminación y guardar no debería salir eliminación si se esta creando producto se debe cambiar este por cancelar. / When entering the product view and going to product creation, two buttons appear, these are delete and save, delete should not appear if a product is being created, this should be changed to cancel.

- [ ]  Cambiar botón de eliminación por cancelar / Change delete button to cancel

image

### PR DESCRIPTION
**Pull request by Eghinner**
#### Screenshots
chrome_Ed7JNyiR3H
chrome_fWOl7Bknoa
chrome_pGxMRYUkMc

### CODE REVIEW

**Comment by angelik0828** [comment]
## ⚠️ Was validated and the following was found

- **When adding a product, it's not just the text, the image needs to be there too.** 

**Current**

image

**Expected result** 

image

**- Image icon missing from profile form**

image


**- In the event view the icon appears but the text below the image does not have the same font as in other views**

image

**Review by Israel-Laguan — APPROVED** [review]

**Comment by Israel-Laguan** [comment]
@angelik0828 please check

**Review by Israel-Laguan — APPROVED** [review]

**Comment by Eghinner** [comment]
> In the event view the icon appears but the text below the image does not have the same font as in other views

I will leave the changes the changes in products view after https://github.com/Azordev/did-admin-panel/pull/219

**Comment by angelik0828** [comment]
## I still don't see the change in these two places

- Add icon change on product creation is not the same as on product edition

image
image

- Change made 

image

**Pull request merged**
