### PR TITLE
style(events): improve styles creae events button

### LINKED ISSUE #65: MEJORAR LA OPCIÓN DEL BOTÓN CREAR EVENTOS / IMPROVE THE CREATE EVENTS BUTTON OPTION
# Explanation

Se puede ver que en la vista de  eventos,  hay una opción que  dice  crear nuevo evento y encontramos que al tocar el botón con el cursor no muestra ninguna reacción el botón debería subrayar 

You can see that in the event view, there is an option that says create new event and we found that touching the button with the cursor does not show any reaction the button should underline or 

## Screenshot

Current appearance:

Image

## Historias de usuario

Yo como usuario quiero que  al tocar con el cursor  al botón crear eventos el  tenga una reacción.

I as a user want that when I touch with the cursor on the create event button he will have a reaction.

## Criterios de aceptación.

el botón  crear eventos  reaccionara al  tener contacto con  el cursor.

the create event button will react to contact with the cursor.

## Casos de uso

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

### PR DESCRIPTION
**Pull request by joset98**
### Description

Please include a summary of the change.

fixes # (issue)

#### Screenshots

If applicable, add screenshots about your changes

#### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How to test it

If applicable, describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

### Checklist:

- [ ] Doesn't break the current code.
- [ ] Passes linters and test, also is building.
- [ ] Doesn't have spelling or grammatical problems.
- [ ] Doesn't have unnecessary comments or debugging code.
- [ ] The branch is updated with the last dev branch changes.

### CODE REVIEW

**Comment by angelik0828** [comment]
## :warning:   Validate the change, I think you can leave the text black when the underline appears

image

**Comment by joset98** [comment]
image

**Review by Eghinner — APPROVED** [review]

**Review by heliomar-pena — APPROVED** [review]
Looks good, good work!

**Comment by Eghinner** [comment]
@joset98 im sorry, this was done by another PR. It will not be merged, but the effort will be validated.

**Pull request closed without merging**
