### PR TITLE
Validation Price #2

### LINKED ISSUE #222: Error al ingresar precio en el valor de productos
# Describe the bug
Al ingresar como proveedor en did admin panel seleccionamos la opción "Añadir nuevo producto", se abre una vista de pantalla con un formulario, pará ingresar una información para el nuevo producto a añadir vemos que en el espacio  de precio de producto  el formato para ingresar el precio del producto es de carácter general la idea es que solo se pueda ingresar solo números  puntos no letras y  demás como esta

# To Reproduce
1. Go to '...' Ingreso como proveedor con credenciales
2. Click on '....'se abre una vista de pantalla con los productos en exhibición selecciono "Añadir nuevo producto"
3. Scroll down to '....' se abre una lista de pantalla donde esta un formulario para ingresar una información del nuevo producto
4. See error  al escribir o ingresar el precio del producto en ese mismo espacio también se pueden agregar letras artediscos guiones ect

# Expected behavior
lo ideal es que en este espacio "Precio del producto" solo se pueda ingresar números y puntos

# Screenshots
1 Asi esta el formato ahora mismo al ingresar cualquier carácter en "Precio del producto"
image

2 Resultado esperado solo se puede ingresar en "Precio del producto" números y puntos

image

### PR DESCRIPTION
**Pull request by Eghinner**
## Steps

1. Login with provider user
2. Got to add product
3. Test price input
## Disclamer
This is a proposal of two, since neither of them convinces me.

## Errors

1. Dont pass validation of type
2. If validation type is disable, fail when try add to DB becuse have a `comma` for decimal

### CODE REVIEW

**Comment by Eghinner** [comment]
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> 
> Name	Status	Preview	Updated
> **did-admin-panel**	❌ Failed ([Inspect](https://vercel.com/azordev/did-admin-panel/CQxK67yXmQbJaa1dRwqMJfAxtrdi))		Sep 14, 2022 at 10:33PM (UTC)

well, I don't have eslint and prettier errors
can you helpme, @e-azocar ?

**Comment by e-azocar** [comment]
@Eghinner 
image
image

**Review by Israel-Laguan — APPROVED** [review]
Check why it's failing to build

**Review by e-azocar — APPROVED** [review]

**Review by heliomar-pena — APPROVED** [review]
@angelik0828 check please

**Pull request closed without merging**
