### PR TITLE
Adding loading message in Products list

### LINKED ISSUE #232: Cambiar el mensaje no hay productos por un mensaje que diga "cargando"
**Describe the bug**
al entrar con usuario y contraseña notamos que  un mensaje que dice "No hay productos", pasa lo mismo cuando se da clic al boton Regresar ya estando en otra vista de pantalla. Cambiar este mensaje por un mensaje que diga "Cargando"

**To Reproduce**

1. Go to '...'Entro con usuario y contraseña
2  See error. Cambiar mensaje de No hay productos por un mensaje que diga Cargando

**Expected behavior**
al entrar  con usuario y contraseña al admin panel did en el cambio de vista de pantalla saldrá un   el mensaje Cargando

**Screenshots**
1 En este ejemplo se puede estimar el mensaje en la parte superior derecha de la pantalla
https://user-images.githubusercontent.com/111365000/190245879-e93bf2cc-09a1-4636-b79a-c89dd76bdd6d.mp4

### PR DESCRIPTION
**Pull request by heliomar-pena**
### Description

Now while is loading a "Loading" message is displayed. After, if the Provider don't have products a message "The provider doesn't have products" is displayed. And if the provider have products then the list is displayed

fixes #232 

#### Screenshots

imagen
lastrecord

#### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How to test it

please check issue for reproductions' steps

### Checklist:

- [x] Doesn't break the current code.
- [x] Passes linters and test, also is building.
- [x] Doesn't have spelling or grammatical problems.
- [x] Doesn't have unnecessary comments or debugging code.
- [x] The branch is updated with the last dev branch changes.

### CODE REVIEW

**Review by Israel-Laguan — APPROVED** [review]

**Comment by Israel-Laguan** [comment]
@angelik0828 please check

**Comment by angelik0828** [comment]
## ✔️ sand valid that:
- When entering the application, a text appears loading in the center of the page
- When navigating the application from the side menu, clicking on profile and then on product, the text loading appears before the list of products.
- ⚠️  when creating a product and then go to product the loading appears but at the top

image

**Comment by heliomar-pena** [comment]
> ## heavy_check_mark sand valid that:
> 
>     * When entering the application, a text appears loading in the center of the page
> 
>     * When navigating the application from the side menu, clicking on profile and then on product, the text loading appears before the list of products.
> 
>     * warning  when creating a product and then go to product the loading appears but at the top
> 
> 
> image

I got it, will work in that

**Comment by heliomar-pena** [comment]
> ## heavy_check_mark sand valid that:
> 
>     * When entering the application, a text appears loading in the center of the page
> 
>     * When navigating the application from the side menu, clicking on profile and then on product, the text loading appears before the list of products.
> 
>     * warning  when creating a product and then go to product the loading appears but at the top
> 

ready the change, please check @angelik0828

**Review by Israel-Laguan — APPROVED** [review]

**Review by Eghinner — APPROVED** [review]

**Pull request merged**
