### PR TITLE
Issue 121 y 96

### PR DESCRIPTION
**Pull request by PrototypeK02**
Botones ya antes creados colocados en lugares donde aun no estaban con estilo, en parte superior, y fondo blanco con nombre de eventos o proveedores
addproviderbtn

### CODE REVIEW

**Comment by Israel-Laguan** [comment]
Please rebase

**Comment by Israel-Laguan** [comment]
Also seems like this is already solved, please check
image
https://www.did-admin.tk/proveedores/crear

image
https://www.did-admin.tk/eventos/crear

**Comment by Israel-Laguan** [comment]
@Eghinner please confirm

**Comment by angelik0828** [comment]
## ✔️ It was necessary to add some styles and he didn't have time to upload the changes he had made, that's why this PR exists, when they wanted to upload it the task was closed, it is so that the task is not incomplete.

https://github.com/Azordev/did-admin-panel/pull/188
https://github.com/Azordev/did-admin-panel/pull/189

**Review by angelik0828 — APPROVED** [review]

**Pull request closed without merging**
