### PR TITLE
feat: Hovering over the menu texts changes color.

### LINKED ISSUE #183: Hovering over the menu texts changes color.
## Acceptance Criteria
- [ ] Define by default each link with gray color (my suggest, opacity: .7)
- [ ] When a view is active, its link changes to white.
- [ ] When hovering, change to white

image
image

_Originally posted by @angelik0828 in https://github.com/Azordev/did-admin-panel/issues/67#issuecomment-1224907119_

# Referencias

- Por favor terminar en 3 días. Mas información: https://github.com/Azordev/did-admin-panel/issues/192

### PR DESCRIPTION
**Pull request by JRS-Developer**
### Description

Now when the user enters a link or hover a link it will show the text an icon of color white.

fixes #183 

#### Screenshots
https://user-images.githubusercontent.com/77207702/188962008-6b642c6a-f53f-491a-8210-c50d43f9235b.mov

#### Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

### How to test it

If applicable, describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

1. Login as administrator
1. Click on any url on the left sidebar

### Checklist:

- [x] Doesn't break the current code.
- [x] Passes linters and test, also is building.
- [x] Doesn't have spelling or grammatical problems.
- [x] Doesn't have unnecessary comments or debugging code.
- [x] The branch is updated with the last dev branch changes.

### CODE REVIEW

**Review by Israel-Laguan — APPROVED** [review]

**Review by heliomar-pena — APPROVED** [review]
Good work!

**Review by e-azocar — APPROVED** [review]

**Review by angelik0828 — APPROVED** [review]
## ✔️ It is validated, when entering the application it enters the event view, this has the change of state of the button in the side menu.

- Events 
image

- Providers
image

- Partners
image

**Review by Luisparr14 — APPROVED** [review]
GJ 🚀

**Comment by Israel-Laguan** [comment]
@Eghinner please check

**Comment by JRS-Developer** [comment]
# UPDATE

@Eghinner 
Now it works with nested urls.

https://user-images.githubusercontent.com/77207702/189430171-948bcb81-7ce4-4905-b299-dbd4b0ab3d59.mov

**Review by Eghinner — APPROVED** [review]
Elegant!!!

**Pull request merged**
