### PR TITLE
Form fields validation, Events and Providers

### LINKED ISSUE #253: Create empty field validations in event creation form and form of  creation of partners
**Explanation**

when creating an event, and not filling in any field and clicking save, there must be validation of empty fields.
It should appear below the text field that the field is empty this for
- Name
- Date
- Hour
- All fields are required

take as a guide the validation of other forms

image

image

### PR DESCRIPTION
**Pull request by PrototypeK02**
### Description

Please include a summary of the change.

Events create validation fields
Provider create validation fields

#### Screenshots

If applicable, add screenshots about your changes

#### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How to test it

If applicable, describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

### Checklist:

- [ ] Doesn't break the current code.
- [ ] Passes linters and test, also is building.
- [ ] Doesn't have spelling or grammatical problems.
- [ ] Doesn't have unnecessary comments or debugging code.
- [ ] The branch is updated with the last dev branch changes.

### CODE REVIEW

**Comment by e-azocar** [comment]
@PrototypeK02 please check this out
image

**Review by Israel-Laguan — APPROVED** [review]
Seems like all the fields are required now?

@Eghinner please check

Also, remove the lockfile change, please

**Comment by PrototypeK02** [comment]
> Seems like all the fields are required now?
> 
> @Eghinner please check
> 
> Also, remove the lockfile change, please

Yes, the custom input component makes the input required, but it wasnt working as a boolean, by default  the required option for the form was false, and the property required from the custom input was a string.

**Comment by angelik0828** [comment]
## :heavy_check_mark: Verification performed found

-The fields, being empty and clicking save, throw the error written below the text field. - events

 image

- In providers, clicking add also shows me the fields with a text below the text field.
image

**Review by angelik0828 — APPROVED** [review]

**Review by e-azocar — APPROVED** [review]

**Review by Eghinner — APPROVED** [review]

**Pull request merged**
