### PR TITLE
feat: no attendee & header attendee

### LINKED ISSUE #225: cuando no hay asistentes, podria salir un mensaje de "No se encuentran asistentes inscritos hasta el momento"

### PR DESCRIPTION
**Pull request by Eghinner**
chrome_Ji7qX1WQFl

### CODE REVIEW

**Review by Israel-Laguan — APPROVED** [review]

**Comment by angelik0828** [comment]
## se encontr que esta funcionando

**Comment by angelik0828** [comment]
## ❌  no funciona
image

**Comment by Israel-Laguan** [comment]
@angelik0828 please check

**Comment by angelik0828** [comment]
## ✔️ Validated when the admin user enters an event and clicks on the attendees, they can see if there is a list of attendees

image
image

**Review by angelik0828 — APPROVED** [review]

**Pull request merged**
